### ISSUE TITLE
Could not pass event PlayerJoinEvent to EcoLobby v1.2.2

### ISSUE THREAD

**Issue by PWNight** [Baraban4ik/EcoLobby#7]
[22:30:38 ERROR]: Could not pass event PlayerJoinEvent to EcoLobby v1.2.2
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at me.baraban4ik.ecolobby.managers.ActionManager.lambda$execute$0(ActionManager.java:63) ~[EcoLobby v1.2.2.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at me.baraban4ik.ecolobby.managers.ActionManager.execute(ActionManager.java:21) ~[EcoLobby v1.2.2.jar:?]
        at me.baraban4ik.ecolobby.listeners.JoinListener.onJoin(JoinListener.java:56) ~[EcoLobby v1.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor28.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-371]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-371]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-371]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:344) ~[paper-1.20.4.jar:git-Paper-371]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[paper-1.20.4.jar:git-Paper-371]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.4.jar:git-Paper-371]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.4.jar:git-Paper-371]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-371]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-371]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-371]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-371]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-371]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-371]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-371]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-371]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:30:38 INFO]: > PWNight попал в Лобби

**Comment by Baraban4ik** [comment]
Не могли бы вы скинуть эту часть конфига?
Could you please discount that part of the config?
```
Join_and_Leave:
  actions: 
```

**Comment by PWNight** [comment]
```
Join_and_Leave:
  # Teleport to spawn when joining a server
  teleport_to_spawn: true
  # Actions to when joining a server
  actions:
    - "[TITLE]&aПриветствуем, %player%"
  # Play music when joining a server
  # NoteBlockAPI required
  music:
    enabled: false
    # You need to place the .nbs file in the tracks folder
    # And select this file here, example: track: "music.nbs".
    track: "music.nbs"
    # NO - Don't repeat
    # YES - Repeat
    repeat: YES

  # Clearing chat when joining a server
  clear_chat: true

  # Clearing items when leaving a server
  clear_items: true
```

**Comment by PWNight** [comment]
Только сейчас заметил, что после [TITLE] нету пробела, думаю проблема в нём

**Comment by Baraban4ik** [comment]
```
Join_and_Leave:
  # Teleport to spawn when joining a server
  teleport_to_spawn: true
  # Actions to when joining a server
  actions:
    - "[TITLE]&aПриветствуем, %player%; "
  # Play music when joining a server
  # NoteBlockAPI required
  music:
    enabled: false
    # You need to place the .nbs file in the tracks folder
    # And select this file here, example: track: "music.nbs".
    track: "music.nbs"
    # NO - Don't repeat
    # YES - Repeat
    repeat: YES

  # Clearing chat when joining a server
  clear_chat: true

  # Clearing items when leaving a server
  clear_items: true
```
